EXERCÍCIO 01

In [283]:
avg_list = [6, 7, 4, 7, 8, 4, 2, 5, 7, 'hum', 'dois']

In [284]:
soma = 0
avg_list[-2:] = 1,2
for n in avg_list:
    soma = soma + n
    result = soma/(len(avg_list))
print(result)

4.818181818181818


EXECÍCIO 02

In [223]:
l1 = [3 * x for x in range(10)]
print(l1)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]


In [253]:
l2 = [3 * x for x in range(10)]
print(l2)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]


def suml1l2():
    s1 = 0
    s2 = 0
    for n1 in l1:
        s1 = s1 + n1
        for n2 in l2:
            s2 = s2 + n2
            resultxpto = s1 + s1
            m_xpto = resultxpto * 2
print(m_xpto)

EXERCÍCIO 03

In [286]:
import numpy as np

In [305]:
nxm = np.arange(35).reshape(7,5)
print(nxm)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


In [308]:
newnxm = np.reshape(nxm,(5,7))
print(newnxm)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [313]:
newnxm.sum(axis=0)

array([ 70,  75,  80,  85,  90,  95, 100])

In [315]:
newnxm.sum(axis=1)

array([ 21,  70, 119, 168, 217])

In [317]:
newnxm.max()

34

In [320]:
newnxm.min()

0

EXERCICIO 04

In [322]:
nxn = np.arange(5).reshape(5)
print(nxn)

[0 1 2 3 4]


In [325]:
result = nxm.sum() + nxn.sum()
print(result)

605


EXERCICIO 05

In [332]:
mtx = np.arange(1001)
print(mtx)

[   0    1    2 ...  998  999 1000]


EXERCÍCIO 06

In [341]:
zero = np.arange(100).reshape(10,10)
zero[0:] = 0
print(zero)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
